services:
  - type: web
    name: snapix
    runtime: node
    region: oregon
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          name: snapix
          type: web
          property: hostUrl
      - key: FACEBOOK_CALLBACK_URL
        value: https://snapix.onrender.com/api/auth/facebook/callback
      - key: N8N_WEBHOOK_URL
        sync: false
      - key: N8N_API_KEY
        sync: false
      - key: FACEBOOK_GRAPH_VERSION
        value: v18.0